change types of fee rates and fix the rounding to 2 problem
chainwayxyz/citrea pull request #1068
Opened 2024-09-02 08:19 UTC by eyusufatik

# Description
without the new round to decimals, we would get 1.00000...02 and that would ceil to 2 sat per vbyte

now it rounds correctly to 8 decimal points + I've changed the return types of fee rates to u64 which should be enough for our calcs

2024-09-02 08:50 UTC, ercecan approved these changes

2024-09-02 13:03 UTC, kpp requested changes
I doubt the current fn round works as expected for all floats

2024-09-02 13:03 UTC, kpp commented on crates/bitcoin-da/src/lib.rs
> +fn round(x: f64, decimals: u32) -> f64 {
https://docs.rs/rust_decimal/latest/rust_decimal/struct.Decimal.html#method.rescale

2024-09-02 13:54 UTC, kpp approved these changes

2024-09-03 15:31 UTC, eyusufatik commented
Refactored for better readability and fixed a few simple mistakes in our tx builders.

We should only use taproot addresses in our wallets from now on.

2024-09-03 19:28 UTC, merged