Erce/implement boundless adapter
chainwayxyz/citrea pull request #1356
Opened 2024-10-18 08:45 UTC by ercecan

# Description

## Linked Issues
- Fixes # (issue, if applicable)
- Related to # (issue) 

## Testing
Describe how these changes were tested. If you've added new features, have you added unit tests?

## Docs
Describe where this code is documented. If it changes a documented interface, have the docs been updated?

2024-10-22 15:38 UTC, rakanalh requested changes

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/Cargo.toml
> +[package]
Sorry but i am very opinionated about introducing crates. Especially this when we have `risc0-bonsai` and `risc0-boundless` where both can live in a single `proving-clients` crate or something like that.

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/src/host.rs
> +// TODO: Remove blocking wrapper once the boundless client has blocking api
This TODO seems to be in the wrong place...

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/src/host.rs
> +        macro_rules! unwrap_boundless_response {
Move macro outside the the impl block.

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/src/host.rs
> +        let join_handle = tokio::spawn(async move {
Move this async block into it's own function... 
```suggestion
        let join_handle = tokio::spawn(handle_response(client))
```

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/src/host.rs
> +            'queue: loop {
1. Is it a good idea to retry indefinitely?
2. Wouldn't it be better if somehow we return an error that the call-site can handle in a backoff-retry fashion or maybe keep `pending` list of requests and retry later? 
3. Handle errors in the call-site for more control over what happens if this keeps failing.

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/src/host.rs
> +        tokio::task::block_in_place(|| rx.blocking_recv().unwrap())
Why use `block_in_place` when you can make this method async + you're calling this method from an async block?

2024-10-22 15:38 UTC, rakanalh commented on crates/risc0-boundless/src/host.rs
> +        // Retry backoff
Is this a TODO? Otherwise, this is not retry-backoff

2025-05-23 09:25 UTC, ercecan commented
Superseded by #2391

2025-05-23 09:25 UTC, closed without merging