Impl guest side verification
chainwayxyz/citrea pull request #1375
Opened 2024-10-24 09:02 UTC by ercecan

# Description
Initial pr that prepares the foundation for #1306 
After merged, for testing Risc0's `FakeReceipt`s will be used with `RISC0_DEV_MODE` enabled

## Linked Issues
- Related to #1306

2024-10-25 22:14 UTC, eyusufatik requested changes

2024-10-25 22:14 UTC, eyusufatik commented on crates/sovereign-sdk/adapters/mock-zkvm/src/lib.rs
> +            sov_rollup_interface::zk::Proof::Mock(pub_input) => {
call this fake receipt or test receipt

2024-10-28 07:13 UTC, eyusufatik requested changes

2024-10-28 07:13 UTC, eyusufatik commented on crates/sovereign-sdk/rollup-interface/src/state_machine/zk/mod.rs
>      /// Only public input was generated.
remove all of this public input stuff, now we have the receipt for execute mode so the output has to be same

2024-10-28 07:13 UTC, eyusufatik commented on crates/prover-services/src/parallel/mod.rs
>                  let journal: Journal = bincode::deserialize(&journal)?;
this should be FakeReceipt now?

2024-10-31 09:00 UTC, ercecan commented
Closing in favor of #1402

2024-10-31 09:00 UTC, closed without merging