Offchain state map: reduce state diff size by removing contract code.
chainwayxyz/citrea pull request #1399
Opened 2024-10-30 16:30 UTC by rakanalh

# Description

## Linked Issues
- Fixes #1351

2024-10-31 08:12 UTC, eyusufatik commented on crates/evm/src/evm/db.rs
>          Ok(self
need to check if keccak(code_from_offchain) == code_hash

2024-11-06 12:21 UTC, eyusufatik requested changes
great pr

evm db check is VERY IMPORTANT though

2024-11-06 12:21 UTC, eyusufatik commented on crates/evm/src/evm/db.rs
> +            .get(&code_hash, &mut self.working_set.offchain_state())
once more this should be like this:

```rust
let code = self
            .code
            .get(&code_hash, &mut self.working_set.offchain_state()

assert_eq!(keccak256(code), code_hash);

Ok(code)
```

or you can return Err as well.

There is nothing preventing us from supplying the wrong code to the offchain witness right now (for zk proving)

2024-11-06 12:21 UTC, eyusufatik commented on crates/evm/src/evm/db_commit.rs
>                      }
create the offchain working set once and use it?

2024-11-07 04:06 UTC, eyusufatik approved these changes

2024-11-07 04:52 UTC, kpp commented
I am not quite sure about this PR. Is this PR equal to

```
--- a/crates/sovereign-sdk/module-system/sov-state/src/prover_storage.rs
+++ b/crates/sovereign-sdk/module-system/sov-state/src/prover_storage.rs
@@ -144,6 +144,7 @@ where
         let batch = state_accesses
             .ordered_writes
             .into_iter()
+            .filter(|(key, _value)| !key.key.starts_with(b"Evm/c"))
             .map(|(key, value)| {
                 let key_hash = KeyHash::with::<DefaultHasher>(key.key.as_ref());
```

?

2024-11-07 08:20 UTC, eyusufatik commented
@kpp that works for not including it in the diff but the code would still end up in the state tree. your solution lacks two important things from the current impl.:

1. The code is still committed to the tree, that means when we use contract code in zk, we still do merkle proof verification, but in this pr, comparing with a code hash is sufficient -> better cycles (esp. when keccak256 accelerator is ready)
2. The code is still committed to the tree, that means when we reconstruct tree from DA, we can't end up in the same state root. But in this pr since we only put the code hash to the state tree, we don't have that problem.

Clever thinking though :)

2024-11-07 09:20 UTC, merged

2024-11-07 14:37 UTC, kpp commented on crates/evm/src/evm/handler.rs
> +                if db_code.is_empty() && !SPEC::enabled(SpecId::CANCUN) {
Why?