Da monitoring service
chainwayxyz/citrea pull request #1407
Opened 2024-11-01 13:49 UTC by jfldde

# Description

- Monitor txs send in `spawn_da_queue`
- Monitor chain re-org and resubmit txs
- Add `DaRpc` server/client
- Add cpfp fee bumping endpoint: `da_bumpFeeCpfp` which takes an Optional<Txid> and a new fee_rate. Bumps latest TX in chain if txid is None
- Add monitoring endpoints : `da_getPendingTransactions`, `da_getTxStatus` and `da_getLastMonitoredTx`
- Revive TX chain on `MonitoringService` initialization and keep as single source of truth for `prev_utxo` and `pending_txs`

## Linked Issues
- Related to #892 

## Tests
- Add a re-org test asserting that txs are properly re-submitted and commitments are part of the updated height post re-org
- Add a cpfp fee bumping test that assert that TX chain is followed.

## Missing
- Add test again full mempool
- Add RBF fee bumping
- Add auto fee bumping trigger if needed

2024-11-04 03:12 UTC, eyusufatik requested changes

2024-11-04 03:12 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
> +                                                    error!(?e, "Failed to monitored tx chain");
monitor*

2024-11-04 03:12 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
> +    ) -> Result<(Vec<Txid>, TxWithId), anyhow::Error> {
Just make it Vec<TxWithId>?

2024-11-04 03:12 UTC, eyusufatik commented on crates/bitcoin-da/src/monitoring.rs
> +const DEFAULT_HISTORY_LIMIT: usize = 1_000; // Keep track of last 1k txs
putting size limitation on the history is probably helpful as well.

2024-11-04 03:12 UTC, eyusufatik commented on crates/bitcoin-da/src/monitoring.rs
> +    Evicted,
what is evicted

2024-11-04 03:12 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
can put monitoring service config under bitcoin service config, that way we can set it through our config toml's

2024-11-04 08:12 UTC, jfldde commented on crates/bitcoin-da/src/monitoring.rs
> +    Evicted,
That would be the TX status if it ever goes from `Pending` to not found in mempool. 
Could be a good trigger for us to bump fee as eviction can happen in time of congestion when a mempool gets full.

2024-11-04 12:16 UTC, jfldde commented on crates/bitcoin-da/src/service.rs
> +    ) -> Result<(Vec<Txid>, TxWithId), anyhow::Error> {
You mean a Vec of `Txid` or `TxWithId` ? 
We need the full Transaction from `TxWithId` to build the `prev_utxo`.
We could hold a Vec of Transaction but we still need to call `gettransaction <txid>` in the monitoring service to fetch the number of confirmations and to assert that it's held in mempool

2024-11-04 15:31 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
> +    ) -> Result<(Vec<Txid>, TxWithId), anyhow::Error> {
Vec of TxWithId

2024-11-06 15:53 UTC, jfldde commented on crates/bitcoin-da/src/monitoring.rs
> +const DEFAULT_HISTORY_LIMIT: usize = 1_000; // Keep track of last 1k txs
Other than the DEFAULT_HISTORY_LIMIT you mean ?

2024-11-06 15:57 UTC, jfldde commented on crates/bitcoin-da/src/service.rs
> +    ) -> Result<(Vec<Txid>, TxWithId), anyhow::Error> {
The TxWithId is used to build the next prev_utxo whereas the Vec<Txid> is used to monitor all the txs.
We don't really need to hold the Transaction itself alongside them since we need to do a gettransaction call anyway to check confirmations.

2024-11-07 04:18 UTC, eyusufatik requested changes

2024-11-07 04:18 UTC, eyusufatik commented on crates/bitcoin-da/src/monitoring.rs
> +const DEFAULT_HISTORY_LIMIT: usize = 1_000; // Keep track of last 1k txs
yeah the size of all txs in history, might be unnecessary though.

but for the prover for example

assume at high traffic for a long time 

400kb for 2 tx groups (commit + reveal)

totals at 195 MB

hmm, that's fine actually

or is the history just txid?

2024-11-07 04:18 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
>                  Ok(Some(prev_utxo)) => Some(prev_utxo),
should we get the prev_utxo from the monitoring service now?

and update it from there so if tx is bumped, we use an output from the bump tx

2024-11-07 04:18 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
> +        }
(referring to my last comment) and if we do it this way, now we don't need to search in the utxo list, the monitoring chain becomes the source of truth for `prev_utxo`

2024-11-07 04:18 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
> +            }
as you keep adding this inputs, you have to recalculate the fee needed to pay since the size of the child increases :)

2024-11-07 07:55 UTC, jfldde commented on crates/bitcoin-da/src/service.rs
> +        }
Sounds good, I'll amend

2024-11-07 16:47 UTC, eyusufatik commented on crates/bitcoin-da/src/service.rs
> +                required_fee = calculate_child_fee(&child_tx);
wouldn't you need total_input >= required_fee + output amount? or smth like that?

2024-11-07 21:40 UTC, jfldde commented on crates/bitcoin-da/src/monitoring.rs
> +const DEFAULT_HISTORY_LIMIT: usize = 1_000; // Keep track of last 1k txs
Sounded good and future proof, added it

2024-11-08 04:10 UTC, eyusufatik requested changes

2024-11-08 04:10 UTC, eyusufatik commented on Cargo.toml
> +bitcoincore-rpc = { version = "0.18.0", git = "https://github.com/chainwayxyz/rust-bitcoincore-rpc.git", rev = "5ce1bed" }
if this closes the bitcoin core rpc bump issue pls add it to the pr sidebar

2024-11-08 04:10 UTC, eyusufatik commented on bin/citrea/tests/bitcoin_e2e/bitcoin_test.rs
> +            .await?;
assert fee is really bumped to where it should be

2024-11-08 09:02 UTC, jfldde commented on Cargo.toml
> +bitcoincore-rpc = { version = "0.18.0", git = "https://github.com/chainwayxyz/rust-bitcoincore-rpc.git", rev = "5ce1bed" }
This is not addressing issue #1364 , only bumping to include https://github.com/chainwayxyz/rust-bitcoincore-rpc/pull/6 RPC typing fix

2024-11-08 10:37 UTC, rakanalh commented on bin/citrea/src/rollup/bitcoin.rs
> +            service.monitoring.clone().spawn().await?;
Please think about how we can use a cancellation token with `ctrl_c` from tokio to support future cancellation for both the da queue service and the monitoring service.

2024-11-08 10:37 UTC, rakanalh commented on crates/bitcoin-da/src/monitoring.rs
> +        tokio::spawn(async move {
Accept a cancellation token as a param to `spawn` and use it here to stop if the cancellation token is triggered.

2024-11-08 10:37 UTC, rakanalh commented on crates/bitcoin-da/src/monitoring.rs
> +    // }
Remove?

2024-11-10 16:18 UTC, jfldde commented on bin/citrea/src/rollup/bitcoin.rs
> +            service.monitoring.clone().spawn().await?;
[efc1ba1](https://github.com/chainwayxyz/citrea/pull/1407/commits/efc1ba1ffe9b49505ceb610d89a54f7dca03d406) Sharing the task manager and handling it via the main loop select

2024-11-13 17:32 UTC, eyusufatik approved these changes

2024-11-13 17:32 UTC, merged