Light client proof bitcoin e2e test
chainwayxyz/citrea pull request #1491
Opened 2024-11-19 13:15 UTC by ercecan

# Description
Tests light client proof with bitcoin e2e framework

## Linked Issues
- Fixes #1466

2024-11-19 13:24 UTC, eyusufatik requested changes

2024-11-19 13:24 UTC, eyusufatik commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        }
why?

2024-11-19 13:24 UTC, eyusufatik commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        assert_eq!(commitments.len(), 4);
can you fix this thing on other tests as well. remmeber our realization about commit / reveal

2024-11-19 13:24 UTC, eyusufatik commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +
can you check if any non-stitchable batch proof tuples were put into the output vec?

2024-11-19 14:00 UTC, jfldde commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        for _ in 0..4 * min_soft_confirmations_per_commitment {
```suggestion
        for _ in 0..min_soft_confirmations_per_commitment * n_conf {
```
Can lift 4 to a var and re-use on the * 4 and 8 below

2024-11-19 14:00 UTC, jfldde commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        da.generate(1u64, None).await?;
```suggestion
        da.generate(1, None).await?;
```

2024-11-19 14:01 UTC, jfldde commented on bin/citrea/tests/bitcoin_e2e/sequencer_commitments.rs
> -        da.wait_mempool_len(1, None).await?;
Good fix, might explain some flakiness

2024-11-19 14:10 UTC, jfldde commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        let mut n_commitments = 4;
Doesn't need to be mut

2024-11-19 15:01 UTC, jfldde approved these changes

2024-11-19 15:59 UTC, eyusufatik approved these changes

2024-11-19 21:06 UTC, jfldde commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +            min_soft_confirmations_per_commitment: 20,
What's the reason for using 20 here ?

2024-11-19 21:07 UTC, jfldde commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +            },
```suggestion
            mempool_conf: SequencerMempoolConfig {
                pending_tx_size: 2000,
                max_account_slots: 1600,
                ..Default::default()
            },
```

2024-11-20 08:07 UTC, ercecan commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +            min_soft_confirmations_per_commitment: 20,
trying to land multiple proofs in a da block, so I need the commitments to be big enough to create two batch proofs

2024-11-21 12:15 UTC, yaziciahmet requested changes

2024-11-21 12:15 UTC, yaziciahmet commented on crates/primitives/src/constants.rs
> -        Some(v) if matches!(v.as_bytes(), b"1" | b"true") => 39700,
test_sequnecer_commitment_threshold test's tx counts should also be updated accordingly.

2024-11-21 12:15 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +            // sequencer.client.http_client().eth_send_raw_transaction(data)
remove comment

2024-11-21 12:15 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        // Ensure that batch proofs is submitted to DA (2x reveal & 2x commit txs)
batch proofs are*

2024-11-21 12:15 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        );
irrelevant

2024-11-21 15:24 UTC, yaziciahmet submitted a review, later dismissed

2024-11-21 15:24 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        da.wait_mempool_len(4, Some(TEN_MINS)).await?;
how are we sure that 4 sequencer commitments in the same DA block is going to generate 2 batch proofs?

2024-11-21 15:24 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        let light_client_proof = lcp.unwrap();
can just unwrap after await

2024-11-21 15:24 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        let light_client_proof2 = lcp2.unwrap();
same

2024-11-21 15:24 UTC, yaziciahmet commented on bin/citrea/tests/bitcoin_e2e/light_client_test.rs
> +        let light_client_proof3 = lcp3.unwrap();
same

2024-11-22 12:17 UTC, eyusufatik approved these changes

2024-11-22 12:31 UTC, merged