Use HexOrNum in ledger RPCs
chainwayxyz/citrea pull request #1535
Opened 2024-11-28 20:51 UTC by jfldde

# Description

- Accept u64 or hex string as input in ledger RPCs

## Linked Issues
- Fixes #1530 

## Testing

```
curl -s -X POST -H 'accept: application/json' -H 'content-type: application/json' -d '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",       
  "params": [
    "0x9c56cd995a89812aa575d691e50a791c83ad62a64416c8e4c64e706b89862b5b"
  ]
}' localhost:12345  | jq ' .result.blockNumber'
"0x1"

curl -s -X POST -H 'accept: application/json' -H 'content-type: application/json' -d '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "ledger_getSoftConfirmationStatus",
  "params": [
    1                                                                   
  ]
}' localhost:12345  | jq                       
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "trusted"
}

curl -s -X POST -H 'accept: application/json' -H 'content-type: application/json' -d '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "ledger_getSoftConfirmationStatus",
  "params": [
    "0x1"                                                               
  ]
}' localhost:12345  | jq                       
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "trusted"
}
```

2024-11-29 08:14 UTC, eyusufatik commented on crates/sovereign-sdk/full-node/sov-ledger-rpc/src/lib.rs
we can import something like alloy::U64 btw. already has all kind of hex ser/de

2024-11-29 09:09 UTC, jfldde commented on crates/sovereign-sdk/full-node/sov-ledger-rpc/src/lib.rs
Much better

2024-11-29 09:22 UTC, jfldde commented on crates/sovereign-sdk/full-node/sov-ledger-rpc/src/lib.rs
Does implement `From<u64>` though, makes it tedious.

2024-12-02 08:24 UTC, eyusufatik requested changes

2024-12-02 08:24 UTC, eyusufatik commented on crates/sovereign-sdk/full-node/sov-ledger-rpc/src/client.rs
>          &self,
there is a [u8; 32] in the above function we forgot to update, can you also update that?

also the (u64, u64) in get_soft_confirmation_range

2024-12-02 09:24 UTC, eyusufatik approved these changes

2024-12-02 11:02 UTC, merged