Prometheus metrics
chainwayxyz/citrea pull request #1589
Opened 2024-12-11 13:17 UTC by rakanalh

# Description

From the referenced issue, the following was the list of metrics to collect:

### All
- [ ] Storage size ( I think this can be fed into prometheus outside the scope of citrea)
- [ ] RPC served in last 5 min (Same as this one, nginx?)
### Sequencer
- [x] Current number txs in mempool
- [ ] Mempool inbound tx/s (Can be calculated from the current number)
- [x] dry_run_transactions execution time
- [x] produce_block transactions execution time
- [ ] (this one will be hard to track so if we cant no problem) avg. wait time for tx in mempool (Can be calculated i believe)
- [x] Send sequencer commitment execution time
- [x] Sequencer commitment number of blocks
- [x] Current L1 block number used in block production
### Full node
- [ ] Sync progress (Not applicable since we have to know sequencer latest L2 vs fullnode or prover current L2)
- [x] Current L2 block number
- [x] Current L1 block number
- [ ] Soft confirmation pull rate (important while syncing) 
- [x] Soft confirmaiton process durations
- [x] L1 scan duration per L1 block
### Prover(s)
- [x] Current L2 block number
- [x] Current L1 blcok number
- [x] Cycle count for each proof
- [x] DA tx mining time

# TODO
- [ ] Implement / Export graphana dashboards to display these metrics.

## Linked Issues
- Fixes #1293

2024-12-11 15:09 UTC, eyusufatik requested changes
apart from the comments, do we also get any metric recorded by `reth-transaction-pool`?

2024-12-11 15:09 UTC, eyusufatik commented on resources/configs/devnet/rollup_config.toml
let's not put any config here. this is considered to be freezed

2024-12-11 15:09 UTC, eyusufatik commented on crates/light-client-prover/src/metrics.rs
> +});
rename this and batch prover metrics different names pls

2024-12-12 13:48 UTC, rakanalh commented
> apart from the comments, do we also get any metric recorded by `reth-transaction-pool`?

Yes. Metrics from our own code & reth will self register and be included in telemetry information we provide for Prometheus.

2024-12-16 10:25 UTC, eyusufatik requested changes

2024-12-16 10:25 UTC, eyusufatik commented on bin/citrea/src/main.rs
> +            MetricKindMask::GAUGE | MetricKindMask::HISTOGRAM,
not everyone's going to run telemetry. let's make it optional in the config. if telemetry config is given, we start the server, if not, we don't.

2024-12-16 11:27 UTC, eyusufatik approved these changes

2024-12-16 11:27 UTC, merged