Fork1 tests v2
chainwayxyz/citrea pull request #1604
Opened 2024-12-12 22:05 UTC by ercecan

2024-12-13 09:39 UTC, eyusufatik requested changes

2024-12-13 09:39 UTC, eyusufatik commented on crates/evm/src/evm/test_data/KZGPointEvaluation.sol
rename this to something like KZGPointEvaluationCaller

2024-12-13 09:39 UTC, eyusufatik commented on crates/evm/src/evm/test_data/KZGPointEvaluation.sol
and also other related structs.

2024-12-13 09:39 UTC, eyusufatik commented on crates/evm/src/tests/fork_tests.rs
> +    // Deploy transient storage contract
fix comment

2024-12-13 09:39 UTC, eyusufatik commented on crates/evm/src/tests/fork_tests.rs
> +    // Deploy transient storage contract
comment

2024-12-13 09:39 UTC, eyusufatik commented on crates/evm/src/tests/fork_tests.rs
> +
make tx on the contract that was deployed before fork1 and see that you can read it from offchain storage afterwards

2024-12-16 09:34 UTC, rakanalh approved these changes

2024-12-16 22:58 UTC, eyusufatik commented
holding on to this pr until we get our upgrade prs merged. because disabling point evaluation precompile needs some changes unfortunately.

2024-12-19 13:12 UTC, eyusufatik requested changes

2024-12-19 13:12 UTC, eyusufatik commented on crates/evm/src/evm/handler.rs
> +            if let Some(kzg_point_evaluation) = precompiles_inner.get_mut(&u64_to_address(0x0A)) {
since we know at what point kzg comes into play, we can remove only then with the index :)

2024-12-19 13:12 UTC, eyusufatik commented on crates/evm/src/evm/handler.rs
> +            if let Some(kzg_point_evaluation) = precompiles_inner.get_mut(&u64_to_address(0x0A)) {
also the costs should not be zero. it should be the same as call gas cost to a regular address with no precompile

2024-12-19 14:11 UTC, eyusufatik approved these changes

2024-12-19 14:11 UTC, merged