Add witness verification on Bridge contract
chainwayxyz/citrea pull request #352
Opened 2024-04-05 15:13 UTC by okkothejawa

# Description
- will be added later

## Linked Issues
- Fixes # (issue, if applicable)
- Related to # (issue) 

## Testing
Describe how these changes were tested. If you've added new features, have you added unit tests?

## Docs
Describe where this code is documented. If it changes a documented interface, have the docs been updated?

2024-04-09 07:19 UTC, eyusufatik commented on crates/evm/src/evm/system_contracts/src/Bridge.sol
> +        // require(BLOCK_HASH_LIST.verifyInclusion(block_hash, wtxId, intermediate_nodes, index), "Transaction is not in block");
why commented out?

2024-04-15 07:51 UTC, ekrembal requested changes

2024-04-15 07:51 UTC, ekrembal commented on crates/evm/src/evm/system_contracts/src/Bridge.sol
> +        bytes block_header;
We don't need this since we have access to witness merkle root with the block height

2024-04-15 07:51 UTC, ekrembal commented on crates/evm/src/evm/system_contracts/src/Bridge.sol
> +    uint256 public verifierCount;
this is Witness script sig input size

we can rename this to requiredSigsCount

2024-04-16 09:46 UTC, ekrembal approved these changes

2024-04-19 09:19 UTC, merged