Add L1 block hash to query response
chainwayxyz/citrea pull request #354
Opened 2024-04-05 15:48 UTC by otaliptus

# Description
eth_getBlockByNumber now returns both l1_fee_rate and l1_block_hash.

Closes #300.

2024-04-05 16:08 UTC, kpp commented on crates/evm/src/evm/primitive_types.rs
> +    pub(crate) last_l1_hash: B256,
```suggestion
    /// The hash of L1 block this L2 block is bound to.
    pub(crate) l1_hash: B256,
```

2024-04-07 17:59 UTC, eyusufatik approved these changes

2024-04-07 19:03 UTC, kpp commented on crates/evm/src/genesis.rs
> +            last_l1_hash: B256::default(),
l1_hash

2024-04-08 09:40 UTC, eyusufatik requested changes

2024-04-08 09:40 UTC, eyusufatik commented on crates/evm/src/hooks.rs
> +        if let Some(l1_hash) = self.last_l1_hash.get(working_set) {
don't rename here

2024-04-08 09:40 UTC, eyusufatik commented on crates/evm/src/query.rs
> +                (
use camelCase here

2024-04-08 10:27 UTC, merged