Remove code hash from EVM genesis config's
chainwayxyz/citrea pull request #360
Opened 2024-04-08 12:51 UTC by otaliptus

# Description
Fixes #356.

2024-04-08 16:32 UTC, eyusufatik requested changes
Are you planning to do the nonce thing in another pr?

2024-04-08 16:32 UTC, eyusufatik commented on bin/test-data/genesis/demo-tests/celestia/evm.json
Delete this

2024-04-08 16:33 UTC, otaliptus commented
Another

2024-04-08 16:36 UTC, otaliptus commented on crates/evm/src/genesis.rs
> +                code: code,
Which one is correct here?

2024-04-08 16:36 UTC, otaliptus commented on crates/evm/src/tests/genesis_tests.rs
> +            code: Bytes::from_hex("0x60606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063a223e05d1461006a578063").unwrap(),
Same

2024-04-08 16:36 UTC, otaliptus commented on crates/evm/src/tests/genesis_tests.rs
> +        "050d41ea04851c5800ba402d42d7a3777ca025feda7c1bd6a272ff9710a4501a"
These were supposed to change, I guess?

2024-04-08 16:38 UTC, eyusufatik requested changes

2024-04-09 08:35 UTC, eyusufatik approved these changes

2024-04-09 08:35 UTC, merged