Implement batch explorer api
chainwayxyz/citrea pull request #472
Opened 2024-05-01 11:39 UTC by ercecan

# Description
Implements batch explorer api

2024-05-01 11:49 UTC, eyusufatik requested changes

2024-05-01 11:49 UTC, eyusufatik commented on batch-explorer/README.md
adding a small readme explaining why we have it here would be nice

2024-05-01 11:49 UTC, eyusufatik commented on batch-explorer/app.py
> +
should be settable by config

2024-05-01 11:49 UTC, eyusufatik commented on batch-explorer/services/l2_rpc.py
can use ethers-py here

2024-05-01 11:49 UTC, eyusufatik commented on batch-explorer/dtos/commitment.py
> +    merkle_root: str
return heights and hashes as well along with urls to explorers

2024-05-02 09:30 UTC, ercecan commented on batch-explorer/services/l2_rpc.py
that is not very well maintained I believe,
I can use web3py?

2024-05-02 19:06 UTC, merged