Add eth_estimateDiffSize
chainwayxyz/citrea pull request #521
Opened 2024-05-08 18:24 UTC by kpp

# Description

## Linked Issues
- Fixes https://github.com/chainwayxyz/citrea/issues/420

## Testing
TODO

## Docs
Adds `eth_estimateDiffSize` endpoint

2024-05-09 22:24 UTC, eyusufatik requested changes

2024-05-09 22:24 UTC, eyusufatik commented on crates/evm/src/query.rs
> +    pub(crate) fn gas_spent(&self) -> U256 {
we can call this method gas_with_l1_overhead imo

2024-05-10 09:21 UTC, rakanalh reviewed
TBH, i am not in favor of using `diff size` as the name.

Delta is what's more commonly used to describe difference between two different values.

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +/// The result of gas/diffsize estimation.
```suggestion
/// The result of gas/delta estimation.
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +    /// L1 diff size.
```suggestion
    /// L1 gas delta.
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +    diff_size: u64,
```suggestion
    delta: u64,
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +pub struct EstimatedDiffSize {
```suggestion
pub struct EstimatedGasDelta {
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +/// Result of estimation of diff size.
```suggestion
/// Result of estimation of delta.
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +    /// Diff size.
```suggestion
    /// Detla.
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +    pub diff_size: U64,
```suggestion
    pub delta: U64,
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +    #[rpc_method(name = "eth_estimateDiffSize")]
```suggestion
    #[rpc_method(name = "eth_estimateGasDelta")]
```

2024-05-10 09:21 UTC, rakanalh commented on crates/evm/src/query.rs
> +    pub fn eth_estimate_diff_size(
```suggestion
    pub fn eth_estimate_gas_delta(
```

2024-05-10 10:31 UTC, rakanalh approved these changes
Thanks to @kpp for clarifying what is meant by diff here.

LGTM

2024-05-10 12:02 UTC, eyusufatik approved these changes

2024-05-10 12:02 UTC, merged