Replace sleeps with `wait_for_*`
chainwayxyz/citrea pull request #634
Opened 2024-05-28 06:51 UTC by rakanalh

# Description
Replace sleep with `wait_for_*`
## Linked Issues
- Fixes #593

2024-05-28 13:06 UTC, eyusufatik requested changes
great enhancement to the codebase 👍

2024-05-28 13:06 UTC, eyusufatik commented on bin/citrea/tests/all_tests.rs
> +const DEFAULT_PROOF_WAIT_DURATION: u64 = 300; // 4 minutes
5 mins :)

2024-05-28 13:06 UTC, eyusufatik commented on bin/citrea/tests/test_helpers/mod.rs
> +pub async fn wait_for_l2_batch(sequencer_client: &TestClient, num: u64, timeout: Option<Duration>) {
let's call wait_for_l2_block

just like the l1 one

2024-05-28 13:06 UTC, eyusufatik commented on bin/citrea/tests/test_helpers/mod.rs
> +pub async fn wait_for_commitment(
i think we should indicate this checks commitments on postgres, the name should reflect that

2024-05-28 13:21 UTC, eyusufatik approved these changes

2024-05-28 13:34 UTC, merged

2024-05-29 07:16 UTC, kpp commented on bin/citrea/tests/sequencer_commitments/mod.rs
> +    citrea::initialize_logging();
This should be commented out

2024-05-29 07:17 UTC, kpp commented on bin/citrea/tests/sequencer_commitments/mod.rs
> +    citrea::initialize_logging();
as well