Add prev_hash to soft confirmations
chainwayxyz/citrea pull request #873
Opened 2024-07-10 13:28 UTC by rakanalh

# Description

## Linked Issues
- Fixes #845

2024-07-11 08:19 UTC, eyusufatik requested changes
great work. only one problem, we pass state root = 0 to all stf modules in the begin_soft_confirmation_hook now. I mostly addressed this in my comments

2024-07-11 08:29 UTC, rakanalh commented on crates/sovereign-sdk/full-node/db/sov-db/src/ledger_db/mod.rs
> +    }
We have it in the RPC handler of the ledger_db... i should change the implementation of the RPC handler to use this

2024-07-11 10:34 UTC, rakanalh commented on crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/lib.rs
>          sequencer_public_key: &[u8],
Done

2024-07-11 10:35 UTC, rakanalh commented on crates/sovereign-sdk/module-system/sov-modules-api/src/hooks.rs
> +            pre_state_root: vec![0; 32], //TODO signed_soft_confirmation_batch.pre_state_root(),
Done

2024-07-11 22:28 UTC, rakanalh commented on crates/sovereign-sdk/full-node/sov-stf-runner/src/runner.rs
https://github.com/chainwayxyz/citrea/issues/881

2024-07-11 22:31 UTC, rakanalh commented on crates/sovereign-sdk/module-system/sov-modules-api/src/hooks.rs
> +            [0u8; 32],
I have changed this functionality already into `HookSoftConfirmationInfo::new`

2024-07-11 22:37 UTC, rakanalh commented on crates/sovereign-sdk/rollup-interface/src/state_machine/zk/mod.rs
> +    pub initial_batch_hash: [u8; 32],
Done

2024-07-12 08:04 UTC, eyusufatik approved these changes

2024-07-12 08:18 UTC, ercecan approved these changes

2024-07-14 13:31 UTC, merged