Fork Manager
chainwayxyz/citrea pull request #922
Opened 2024-07-25 16:38 UTC by rakanalh

# Description

## Linked Issues
- Related to #235

2024-07-30 13:37 UTC, kpp commented on crates/primitives/src/error.rs
> +    MissingL2(&'static str, u64, u64),
Can we have named fields?

2024-07-31 21:56 UTC, eyusufatik requested changes

2024-07-31 21:56 UTC, eyusufatik commented on crates/primitives/src/fork/migration.rs
> +    }
i gave this some thought, what about only having a single on activation fork?

when spec activate height is reached, function is called before everything else.

2024-08-09 09:20 UTC, eyusufatik approved these changes

2024-08-11 09:27 UTC, merged