chore: Bitcoin RPC cleanup
chainwayxyz/citrea pull request #931
Opened 2024-07-29 08:55 UTC by jfldde

# Description

- Consistent use of `anyhow::Result`
- Use type inference 
- Stricter type usage

# Notes:

Have we considered using a library such as like https://github.com/rust-bitcoin/rust-bitcoincore-rpc/ instead of re-implementing it ourselves ? It comes with a few footguns we will need to be mindful of

2024-07-29 13:05 UTC, kpp requested changes
This makes little sense if we may use https://github.com/Sovereign-Labs/sov-bitcoin-adapter/blob/nightly/src/service/rpc/mod.rs .

I am going to replace anyhow to a proper RpcError, because we need to se-send tx (reveal) in case the previous (commit) hasn't been processed yet.

2024-07-31 21:46 UTC, eyusufatik commented
> This makes little sense if we may use https://github.com/Sovereign-Labs/sov-bitcoin-adapter/blob/nightly/src/service/rpc/mod.rs . I am going to replace anyhow to a proper RpcError, because we need to se-send tx (reveal) in case the previous (commit) hasn't been processed yet.

i also didn't understand. @kpp can you please elobrate?

2024-07-31 21:46 UTC, eyusufatik approved these changes

2024-08-02 16:22 UTC, eyusufatik commented
@kpp explained to me on slack what he meant. we'll do that on another pr

2024-08-02 16:24 UTC, kpp approved these changes

2024-08-02 16:25 UTC, merged