Use Borsh ser/deser in TransactionWrapper and BitcoinHeaderWrapper
chainwayxyz/citrea pull request #933
Opened 2024-07-31 09:00 UTC by jfldde

# Description

- Implement `BorshSerialize` and `BorshDeserializaiton` on `TransactionWrapper` and `BitcoinHeaderWrapper` by manually ser/deser every inner fields
- Remove usage of bitcoin consensus encoding

2024-07-31 21:48 UTC, eyusufatik reviewed
what gains do we get from not using consensus encode? which is very similar to borsh encode when you think about it btw.

2024-08-02 15:46 UTC, yaziciahmet requested changes

2024-08-02 15:46 UTC, yaziciahmet commented on crates/bitcoin-da/src/spec/header.rs
>  pub struct BitcoinHeaderWrapper {
If it's just a wrapper, imo it's better to have it as `pub struct BitcoinHeaderWrapper(BitcoinHeader)`

2024-08-02 15:46 UTC, yaziciahmet commented on crates/bitcoin-da/src/spec/header.rs
> +#[derive(Clone, PartialEq, Eq, Debug, Hash, Serialize, Deserialize)]
Do we still need serde derives?

2024-08-02 15:46 UTC, yaziciahmet commented on crates/bitcoin-da/src/spec/transaction.rs
>  pub struct TransactionWrapper {
Same wrapper suggestion as above

2024-08-02 16:27 UTC, eyusufatik commented
can you do benchmarks on test_all_flow? if you don't have the right commands let me know over slack. also @yaziciahmet recently asked me those commands as well.

2024-08-05 12:14 UTC, yaziciahmet approved these changes

2024-08-06 11:16 UTC, kpp commented
Actually it would be better to test borsh in isolation - only to de-serialize inputs and exit, because now it takes only a small portion of our execution (less then 1% of total cycles). @yaziciahmet did it in https://github.com/chainwayxyz/citrea/pull/943 for comparison.

2024-08-06 11:18 UTC, eyusufatik commented
> Actually it would be better to test borsh in isolation - only to de-serialize inputs and exit, because now it takes only a small portion of our execution (less then 1% of total cycles). @yaziciahmet did it in https://github.com/chainwayxyz/citrea/pull/943 for comparison.

yes let's do it

2024-08-09 09:04 UTC, eyusufatik commented
> can you do benchmarks on test_all_flow? if you don't have the right commands let me know over slack. also @yaziciahmet recently asked me those commands as well.

forgot these were tests on MockDA. we should wait for merge until @jfldde 's bitcoin e2e testing stuff is ready and then benchmark.

2024-08-13 20:41 UTC, yaziciahmet commented
With the merge of #973 , new bitcoin 0.32.2 version has changed the consensus_encode mechanism, and it is no longer usable with the Borsh ser/de. We tried couple of different methods to read/write from and to Borsh to consensus encodable, but it failed. I tested this PR and it seems to solve this issue. It might be required now that we merge this PR in @eyusufatik @kpp

2024-08-13 21:09 UTC, merged