Use bitcoincore-rpc client in BitcoinService
chainwayxyz/citrea pull request #942
Opened 2024-08-02 14:17 UTC by jfldde

# Description

- [Extract background task out of service creation](https://github.com/chainwayxyz/citrea/commit/ea8da33384845e1f1a78aa600e34a6e746006b0d). Remove side effects from `BitcoinService::new()`
- [Use bitcoin::Network directly](https://github.com/chainwayxyz/citrea/commit/83aba16a008911ffca64ae0968e17a1698f1eba7). Stricter typing
- [Remove Clone bound on DaService](https://github.com/chainwayxyz/citrea/commit/894eeabf54b0c3a1e2883a8cfe544dba13a1d02f). Use of Arc to explicit BitcoinService being shared between thread. 
- [Use bitconcore-rpc client instead of BitcoinNode](https://github.com/chainwayxyz/citrea/commit/715cfdae01978b74590e5ecc64bb0b423249fdb9) Removes the need for custom RPC implementation. Removes `crates/bitcoin-da/src/rpc.rs`
- Future proof BitcoinService RPCs usage. 
- Removes `reqwest` && `base64` dependencies

## Linked Issues
- Pre-requisite for https://github.com/chainwayxyz/citrea/issues/892

2024-08-05 12:03 UTC, yaziciahmet commented on Cargo.toml
> +bitcoincore-rpc = { version = "0.18.0", git = "https://github.com/jfldde/rust-bitcoincore-rpc.git" }
my man... don't tell me you are trying to take over the world by installing malware from your local repository.

2024-08-05 12:07 UTC, yaziciahmet commented on crates/bitcoin-da/src/helpers/parsers.rs
> -#[cfg(any(feature = "native", test))]
any idea why this was enabled only on native in the first place?

2024-08-05 12:26 UTC, yaziciahmet requested changes

2024-08-05 12:26 UTC, yaziciahmet commented on crates/bitcoin-da/src/service.rs
> +    pub fn spawn_bg_task(
Maybe give it a more explicit name? Like `spawn_tx_handler`

2024-08-05 12:26 UTC, yaziciahmet commented on crates/bitcoin-da/src/service.rs
> +        let sat_vb_ceil = (btc_vkb * 100_000_000.0 / 1000.0).ceil() as u128;
Seeing this for the second time, maybe separate this into it's own method `estimate_smart_fee`?

2024-08-05 12:33 UTC, yaziciahmet commented on crates/bitcoin-da/src/service.rs
> +    pub fn spawn_bg_task(
For sure

2024-08-06 08:19 UTC, eyusufatik approved these changes

2024-08-06 08:20 UTC, yaziciahmet approved these changes

2024-08-06 08:20 UTC, merged