Sort commitments in zk
chainwayxyz/citrea pull request #987
Opened 2024-08-14 08:05 UTC by yaziciahmet

# Description
Sorting commitments in zk env just in case.

## Linked Issues
- Fixes #985

2024-08-14 08:16 UTC, rakanalh requested changes

2024-08-14 08:16 UTC, rakanalh commented on crates/sovereign-sdk/module-system/sov-modules-stf-blueprint/src/lib.rs
> +            .sort_unstable_by(|c1, c2| c1.l2_end_block_number.cmp(&c2.l2_end_block_number));
In #983 i am sorting by key
```
sequencer_commitments.sort_by_key(|commitment| commitment.l2_start_block_number);
```

I do think we should use the same sort for consistency

2024-08-14 09:13 UTC, eyusufatik approved these changes
aggree with rakan.

2024-08-15 07:56 UTC, rakanalh approved these changes

2024-08-15 07:57 UTC, merged